kind: pipeline
type: docker
name: solid-budget-client

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --single-branch --branch $DRONE_SOURCE_BRANCH --depth=1 $DRONE_GIT_HTTP_URL .
    when:
      branch:
        - main
      event:
        - push
        - pull_request
        - tag

  - name: embed-vars-dev
    image: alpine/git
    commands:
      - export REACT_APP_SB_VERSION=${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - main
      event:
        - push

  - name: embed-vars
    image: alpine/git
    commands:
      - export REACT_APP_SB_VERSION=${DRONE_TAG}
    when:
      branch:
        - main
      event:
        - tag

  - name: build
    image: node:latest
    commands:
      - . ./.env
      - npm install
      - npm run build
    when:
      branch:
        - main
      event:
        - push
        - pull_request
        - tag

  - name: publish-dev
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: paulwrubel/solid-budget-client
      tags:
        - dev
        - ${DRONE_COMMIT_SHA:0:8}
    when:
      branch:
        - main
      event:
        - push

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: paulwrubel/solid-budget-client
      tags:
        - latest
        - ${DRONE_TAG##v}
    when:
      branch:
        - main
      event:
        - tag
